### ISSUE TITLE
Incompatible with 1.4.6

### ISSUE THREAD

**Issue by mdorman** [geigerzaehler/beets-alternatives#13]
Looks like calls to `item.move()` need to be adjusted to handle the changes in https://github.com/beetbox/beets/commit/0a1db4218fdf2b764cd19ee94ac99e88090950a3

**Comment by Profpatsch** [comment]
These are the tests that fail:

```
======================================================================
ERROR: test_external (cli_test.DocTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 31, in test_external
    self.add_album(artist='Bach', title='was mp3', format='mp3')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 186, in add_album
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
musicbrainzngs: DEBUG: set user-agent to beets/1.4.6 python-musicbrainzngs/0.5 ( http://beets.io/ )
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_symlink_view (cli_test.DocTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 77, in test_symlink_view
    self.add_album(artist='Michael Jackson', album='Thriller', year='1982')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 186, in add_album
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_convert (cli_test.ExternalConvertTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 242, in test_convert
    item = self.add_track(myexternal='true', format='mp4')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_convert_and_embed (cli_test.ExternalConvertTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 251, in test_convert_and_embed
    album = self.add_album(myexternal='true', format='m4a')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 186, in add_album
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_skip_convert_for_alternative_format (cli_test.ExternalConvertTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 271, in test_skip_convert_for_alternative_format
    item = self.add_track(myexternal='true')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_skip_convert_for_same_format (cli_test.ExternalConvertTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 262, in test_skip_convert_for_same_format
    item = self.add_track(myexternal='true')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_add_album (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 107, in test_add_album
    album = self.add_album()
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 186, in add_album
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_add_nonexistent (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 115, in test_add_nonexistent
    item = self.add_external_track('myexternal')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 210, in add_external_track
    item = self.add_track(**kwargs)
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_add_replace (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 123, in test_add_replace
    item = self.add_external_track('myexternal')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 210, in add_external_track
    item = self.add_track(**kwargs)
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_add_singleton (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 101, in test_add_singleton
    item = self.add_track(title=u'\u00e9', myexternal='true')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_move_after_path_format_update (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 154, in test_move_after_path_format_update
    item = self.add_external_track('myexternal')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 210, in add_external_track
    item = self.add_track(**kwargs)
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_move_after_tags_changed (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 167, in test_move_after_tags_changed
    item = self.add_external_track('myexternal')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 210, in add_external_track
    item = self.add_track(**kwargs)
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_no_udpdate_newer (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 143, in test_no_udpdate_newer
    item = self.add_external_track('myexternal')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 210, in add_external_track
    item = self.add_track(**kwargs)
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_prune_after_move (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 181, in test_prune_after_move
    item = self.add_external_track('myexternal')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 210, in add_external_track
    item = self.add_track(**kwargs)
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_remove_album (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 205, in test_remove_album
    album = self.add_external_album('myexternal')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 216, in add_external_album
    album = self.add_album(**kwargs)
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 186, in add_album
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_remove_item (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 192, in test_remove_item
    item = self.add_external_track('myexternal')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 210, in add_external_track
    item = self.add_track(**kwargs)
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_update_older (cli_test.ExternalCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 132, in test_update_older
    item = self.add_external_track('myexternal')
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 210, in add_external_track
    item = self.add_track(**kwargs)
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ask_create_no (cli_test.ExternalRemovableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 302, in test_ask_create_no
    item = self.add_track()
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ask_create_yes (cli_test.ExternalRemovableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 294, in test_ask_create_yes
    item = self.add_track()
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_create_option (cli_test.ExternalRemovableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 310, in test_create_option
    item = self.add_track()
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_no_create_option (cli_test.ExternalRemovableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 316, in test_no_create_option
    item = self.add_track()
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_not_removable (cli_test.ExternalRemovableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/cli_test.py", line 322, in test_not_removable
    item = self.add_track()
  File "/tmp/nix-build-beets-alternatives-0.8.2.drv-0/source/test/helper.py", line 204, in add_track
    item.move(copy=True)
TypeError: move() got an unexpected keyword argument 'copy'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

Name                        Stmts   Miss  Cover
-----------------------------------------------
beetsplug/alternatives.py     233    160    31%
----------------------------------------------------------------------
Ran 23 tests in 2.046s

FAILED (errors=22)
```

**Comment by mdorman** [comment]
It's literally everything that depends on the move() interface.

**Comment by wisp3rwind** [comment]
In fact, nothing depends on the move interface, it's only the test setup code. I maintain a personal fork with a bunch of fixes such as for this at [my account](https://github.com/wisp3rwind/beets-alternatives).

In principle, I'd like to work towards inclusion in beets itself or promote that to pypi (assuming that @geigerzaehler is indeed not interested in maintaining this repository anymore). I don't feel sufficiently confident about my changes and about maintaining a relatively well-known plugin such as this, however. Also, right now, I mostly lack the time to do so... So at your own risk, there's a fix at that link.

**Comment by geigerzaehler** [comment]
@wisp3rwind: How do feel about porting some of your changes back to this repo? Please also reach out to me if your interested in maintaining this project.

**Comment by wisp3rwind** [comment]
Hi, nice to see you back here! I'm still actively using the plugin, so I'll happily invest the time to backport my changes. Would you prefer individual PRs or a combined one for all of it?

About maintaining the project, what I said in my previous comment in principle still applies: I don't feel that confident about it (maybe I should nevertheless do it). How much do you care about the plugin/beets right now; would you keep accepting PRs and doing occasional releases, or prefer to rid yourself of that workload or maybe share the work? If you prefer we can also discuss this in private, mail me at the address on my profile.

**Comment by geigerzaehler** [comment]
*Moving to private channels*
