### ISSUE TITLE
beet completion crashes with lastest git

### ISSUE THREAD

**Issue by arlllk** [geigerzaehler/beets-alternatives#38]
When trying to run beet completion with the latest git of beets and beets-alternatives

> beets-alternatives 0.10.0.r0.g5751eb7

> beets version 1.5.0
> Python version 3.7.4
> plugins: absubmit, acousticbrainz, alternatives, artistcountry, badfiles, beatport, chroma, convert, discogs, duplicates, edit, embedart, export, fetchart, filefilter, fromfilename, ftintitle, fuzzy, hook, ihate, importfeeds, info, lastimport, lyrics, mbsubmit, mbsync, metasync, missing, playlist, random, replaygain, rewrite, smartplaylist, thumbnails, web

fails with 
```
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.5.0', 'console_scripts', 'beet')()
  File "/usr/lib/python3.7/site-packages/beets/ui/__init__.py", line 1267, in main
    _raw_main(args)
  File "/usr/lib/python3.7/site-packages/beets/ui/__init__.py", line 1254, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.7/site-packages/beets/ui/commands.py", line 1707, in print_completion
    for line in completion_script(default_commands + plugins.commands()):
  File "/usr/lib/python3.7/site-packages/beets/ui/commands.py", line 1748, in completion_script
    for opts in cmd.parser._get_all_options()[1:]:
AttributeError: 'ArgumentParser' object has no attribute '_get_all_options'

```
[full output]( https://pastebin.com/TYztVdc8)

**Comment by geigerzaehler** [comment]
Thanks for the report @arlllk. I prepared a fix in #39. As soon as that PR is reviewed and merged I will release a new version.
